name: CI

on:
  pull_request:
    paths-ignore:
    - '**.rst'
    - '**.txt'
    - '**.texi'
  push:
    paths-ignore:
    - '**.txt'
    - '**.rst'
    - '**.texi'
    branches-ignore:
    - 'master'
    - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        emacs_version: [29.2, 30.2, 31.1]

    steps:
    - uses: actions/checkout@v6

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: paths
      run: |
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV

    - name: apt-get
      run: |
        sudo apt-get -yq update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gnutls-bin sharutils gnupg2 dirmngr libreadline-dev libcurl4-openssl-dev clangd

    - uses: actions/checkout@v4
      with:
        repository: dickmao/epkg
        path: epkg

    - name: epkg
      run: make -C epkg install

    - name: test
      run: |
        make test
        make install
